defaults:
  - view_sampler: bounded_re10k

name: re10k
roots: [datasets/re10k]
make_baseline_1: false
augment: true

input_image_shape: [180, 320]
original_image_shape: [180, 320]
background_color: [0.0, 0.0, 0.0]
cameras_are_circular: false

baseline_epsilon: 1e-3
max_fov: 100.0

skip_bad_shape: true
near: -1.
far: -1.
baseline_scale_bounds: true
shuffle_val: true
test_len: -1
